### ISSUE TITLE
Twig Language Extension Error

### ISSUE THREAD

**Issue by markvinic** [zed-industries/extensions#1718]
### Check for existing issues

- [X] Completed

### Misc notes

I Love Zed Editor! It's a great tool and have awesome features. I tested it with a rust project and is wonderful to code. With a PHP project too. But, I'm trying with Symfony 7.1 and Twig Extension still emit a error:

Language server error: twig-language-server

The extension:

![Captura de tela de 2024-11-27 09-06-01](https://github.com/user-attachments/assets/6635a5ec-157d-4877-b87e-2501b29326a3)

The log error:

<details><summary>Error</summary>

```txt
0 verbose cli /home/vinicius/.nvm/versions/node/v22.11.0/bin/node /home/vinicius/.nvm/versions/node/v22.11.0/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/npmrc
4 silly config load:file:/home/vinicius/.local/share/zed/extensions/work/twig/.npmrc
5 silly config load:file:/home/vinicius/.local/share/zed/node/blank_user_npmrc
6 silly config load:file:/home/vinicius/.local/share/zed/node/blank_global_npmrc
7 verbose title npm install twig-language-server@0.5.1
8 verbose argv "install" "--cache" "/home/vinicius/.local/share/zed/node/cache" "--userconfig" "/home/vinicius/.local/share/zed/node/blank_user_npmrc" "--globalconfig" "/home/vinicius/.local/share/zed/node/blank_global_npmrc" "twig-language-server@0.5.1" "--save-exact" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000" "--prefix" "/home/vinicius/.local/share/zed/extensions/work/twig"
9 verbose logfile logs-max:10 dir:/home/vinicius/.local/share/zed/node/cache/_logs/2024-11-27T12_51_39_063Z-
10 verbose logfile /home/vinicius/.local/share/zed/node/cache/_logs/2024-11-27T12_51_39_063Z-debug-0.log
11 silly logfile start cleaning logs, removing 2 files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest twig-language-server@0.5.1
16 silly packumentCache full:https://registry.npmjs.org/twig-language-server cache-miss
17 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
18 http fetch GET 200 https://registry.npmjs.org/twig-language-server 70ms (cache hit)
19 silly packumentCache full:https://registry.npmjs.org/twig-language-server set size:17197 disposed:false
20 silly placeDep ROOT twig-language-server@0.5.1 OK for:  want: 0.5.1
21 silly fetch manifest tree-sitter-twig@^0.4.0
22 silly packumentCache full:https://registry.npmjs.org/tree-sitter-twig cache-miss
23 silly fetch manifest vscode-languageserver@^8.1.0
24 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver cache-miss
25 silly fetch manifest vscode-languageserver-textdocument@^1.0.8
26 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-textdocument cache-miss
27 silly fetch manifest vscode-uri@^3.0.7
28 silly packumentCache full:https://registry.npmjs.org/vscode-uri cache-miss
29 silly fetch manifest web-tree-sitter@^0.20.8
30 silly packumentCache full:https://registry.npmjs.org/web-tree-sitter cache-miss
31 http fetch GET 200 https://registry.npmjs.org/web-tree-sitter 418ms (cache revalidated)
32 silly packumentCache full:https://registry.npmjs.org/web-tree-sitter set size:113903 disposed:false
33 http fetch GET 200 https://registry.npmjs.org/vscode-uri 421ms (cache revalidated)
34 silly packumentCache full:https://registry.npmjs.org/vscode-uri set size:75569 disposed:false
35 http fetch GET 200 https://registry.npmjs.org/vscode-languageserver 426ms (cache revalidated)
36 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver set size:696816 disposed:false
37 http fetch GET 200 https://registry.npmjs.org/vscode-languageserver-textdocument 1053ms (cache revalidated)
38 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-textdocument set size:66497 disposed:false
39 http fetch GET 200 https://registry.npmjs.org/tree-sitter-twig 1065ms (cache revalidated)
40 silly packumentCache full:https://registry.npmjs.org/tree-sitter-twig set size:9421 disposed:false
41 silly placeDep ROOT tree-sitter-twig@0.4.0 OK for: twig-language-server@0.5.1 want: ^0.4.0
42 silly placeDep ROOT vscode-languageserver@8.1.0 OK for: twig-language-server@0.5.1 want: ^8.1.0
43 silly placeDep ROOT vscode-languageserver-textdocument@1.0.12 OK for: twig-language-server@0.5.1 want: ^1.0.8
44 silly placeDep ROOT vscode-uri@3.0.8 OK for: twig-language-server@0.5.1 want: ^3.0.7
45 silly placeDep ROOT web-tree-sitter@0.20.8 OK for: twig-language-server@0.5.1 want: ^0.20.8
46 silly fetch manifest vscode-languageserver-protocol@3.17.3
47 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-protocol cache-miss
48 http fetch GET 200 https://registry.npmjs.org/vscode-languageserver-protocol 309ms (cache revalidated)
49 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-protocol set size:466404 disposed:false
50 silly placeDep ROOT vscode-languageserver-protocol@3.17.3 OK for: vscode-languageserver@8.1.0 want: 3.17.3
51 silly fetch manifest vscode-jsonrpc@8.1.0
52 silly packumentCache full:https://registry.npmjs.org/vscode-jsonrpc cache-miss
53 silly fetch manifest vscode-languageserver-types@3.17.3
54 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types cache-miss
55 http fetch GET 200 https://registry.npmjs.org/vscode-languageserver-types 109ms (cache revalidated)
56 silly packumentCache full:https://registry.npmjs.org/vscode-languageserver-types set size:304524 disposed:false
57 http fetch GET 200 https://registry.npmjs.org/vscode-jsonrpc 690ms (cache revalidated)
58 silly packumentCache full:https://registry.npmjs.org/vscode-jsonrpc set size:366417 disposed:false
59 silly placeDep ROOT vscode-jsonrpc@8.1.0 OK for: vscode-languageserver-protocol@3.17.3 want: 8.1.0
60 silly placeDep ROOT vscode-languageserver-types@3.17.3 OK for: vscode-languageserver-protocol@3.17.3 want: 3.17.3
61 silly reify moves {}
62 silly audit bulk request {
62 silly audit   '@isaacs/cliui': [ '8.0.2' ],
62 silly audit   '@npmcli/agent': [ '2.2.2' ],
62 silly audit   '@npmcli/fs': [ '3.1.1' ],
62 silly audit   '@pkgjs/parseargs': [ '0.11.0' ],
62 silly audit   abbrev: [ '2.0.0' ],
62 silly audit   'agent-base': [ '7.1.1' ],
62 silly audit   'aggregate-error': [ '3.1.0' ],
62 silly audit   'ansi-regex': [ '6.1.0', '5.0.1' ],
62 silly audit   'ansi-styles': [ '6.2.1', '4.3.0' ],
62 silly audit   'balanced-match': [ '1.0.2' ],
62 silly audit   'brace-expansion': [ '1.1.11', '2.0.1' ],
62 silly audit   cacache: [ '18.0.4' ],
62 silly audit   glob: [ '10.4.5', '7.2.3' ],
62 silly audit   minimatch: [ '9.0.5', '3.1.2', '3.0.8' ],
62 silly audit   chownr: [ '2.0.0' ],
62 silly audit   'clean-stack': [ '2.2.0' ],
62 silly audit   cli: [ '1.0.1' ],
62 silly audit   'color-convert': [ '2.0.1' ],
62 silly audit   'color-name': [ '1.1.4' ],
62 silly audit   'concat-map': [ '0.0.1' ],
62 silly audit   'console-browserify': [ '1.1.0' ],
62 silly audit   'core-util-is': [ '1.0.3' ],
62 silly audit   'cross-spawn': [ '7.0.5' ],
62 silly audit   isexe: [ '2.0.0', '3.1.1' ],
62 silly audit   which: [ '2.0.2', '4.0.0' ],
62 silly audit   'date-now': [ '0.1.4' ],
62 silly audit   debug: [ '4.3.7' ],
62 silly audit   'dom-serializer': [ '0.2.2' ],
62 silly audit   domelementtype: [ '2.3.0', '1.3.1' ],
62 silly audit   entities: [ '2.2.0', '1.0.0' ],
62 silly audit   domhandler: [ '2.3.0' ],
62 silly audit   domutils: [ '1.5.1' ],
62 silly audit   eastasianwidth: [ '0.2.0' ],
62 silly audit   'emoji-regex': [ '9.2.2', '8.0.0' ],
62 silly audit   encoding: [ '0.1.13' ],
62 silly audit   'env-paths': [ '2.2.1' ],
62 silly audit   'err-code': [ '2.0.3' ],
62 silly audit   exit: [ '0.1.2' ],
62 silly audit   'exponential-backoff': [ '3.1.1' ],
62 silly audit   'foreground-child': [ '3.3.0' ],
62 silly audit   'fs-minipass': [ '3.0.3', '2.1.0' ],
62 silly audit   'fs.realpath': [ '1.0.0' ],
62 silly audit   'graceful-fs': [ '4.2.11' ],
62 silly audit   htmlparser2: [ '3.8.3' ],
62 silly audit   'http-cache-semantics': [ '4.1.1' ],
62 silly audit   'http-proxy-agent': [ '7.0.2' ],
62 silly audit   'https-proxy-agent': [ '7.0.5' ],
62 silly audit   'iconv-lite': [ '0.6.3' ],
62 silly audit   imurmurhash: [ '0.1.4' ],
62 silly audit   'indent-string': [ '4.0.0' ],
62 silly audit   inflight: [ '1.0.6' ],
62 silly audit   inherits: [ '2.0.4' ],
62 silly audit   'ip-address': [ '9.0.5' ],
62 silly audit   'is-fullwidth-code-point': [ '3.0.0' ],
62 silly audit   'is-lambda': [ '1.0.1' ],
62 silly audit   isarray: [ '0.0.1' ],
62 silly audit   jackspeak: [ '3.4.3' ],
62 silly audit   jsbn: [ '1.1.0' ],
62 silly audit   jshint: [ '2.13.6' ],
62 silly audit   lodash: [ '4.17.21' ],
62 silly audit   'lru-cache': [ '10.4.3' ],
62 silly audit   'make-fetch-happen': [ '13.0.1' ],
62 silly audit   minipass: [ '7.1.2', '3.3.6', '5.0.0' ],
62 silly audit   'minipass-collect': [ '2.0.1' ],
62 silly audit   'minipass-fetch': [ '3.0.5' ],
62 silly audit   'minipass-flush': [ '1.0.5' ],
62 silly audit   'minipass-pipeline': [ '1.2.4' ],
62 silly audit   'minipass-sized': [ '1.0.3' ],
62 silly audit   minizlib: [ '2.1.2' ],
62 silly audit   mkdirp: [ '1.0.4' ],
62 silly audit   ms: [ '2.1.3' ],
62 silly audit   nan: [ '2.22.0' ],
62 silly audit   negotiator: [ '0.6.4' ],
62 silly audit   'node-gyp': [ '10.2.0' ],
62 silly audit   nopt: [ '7.2.1' ],
62 silly audit   once: [ '1.4.0' ],
62 silly audit   'p-map': [ '4.0.0' ],
62 silly audit   'package-json-from-dist': [ '1.0.1' ],
62 silly audit   'path-is-absolute': [ '1.0.1' ],
62 silly audit   'path-key': [ '3.1.1' ],
62 silly audit   'path-scurry': [ '1.11.1' ],
62 silly audit   'proc-log': [ '4.2.0' ],
62 silly audit   'promise-retry': [ '2.0.1' ],
62 silly audit   'readable-stream': [ '1.1.14' ],
62 silly audit   retry: [ '0.12.0' ],
62 silly audit   'safer-buffer': [ '2.1.2' ],
62 silly audit   semver: [ '7.6.3' ],
62 silly audit   'shebang-command': [ '2.0.0' ],
62 silly audit   'shebang-regex': [ '3.0.0' ],
62 silly audit   'signal-exit': [ '4.1.0' ],
62 silly audit   'smart-buffer': [ '4.2.0' ],
62 silly audit   socks: [ '2.8.3' ],
62 silly audit   'socks-proxy-agent': [ '8.0.4' ],
62 silly audit   'sprintf-js': [ '1.1.3' ],
62 silly audit   ssri: [ '10.0.6' ],
62 silly audit   string_decoder: [ '0.10.31' ],
62 silly audit   'string-width': [ '5.1.2', '4.2.3' ],
62 silly audit   'strip-ansi': [ '6.0.1', '7.1.0' ],
62 silly audit   'strip-json-comments': [ '1.0.4' ],
62 silly audit   tar: [ '6.2.1' ],
62 silly audit   'unique-filename': [ '3.0.0' ],
62 silly audit   'unique-slug': [ '4.0.0' ],
62 silly audit   'wrap-ansi': [ '8.1.0', '7.0.0' ],
62 silly audit   wrappy: [ '1.0.2' ],
62 silly audit   yallist: [ '4.0.0' ],
62 silly audit   'twig-language-server': [ '0.5.1' ],
62 silly audit   'tree-sitter-twig': [ '0.4.0' ],
62 silly audit   'vscode-languageserver': [ '8.1.0' ],
62 silly audit   'vscode-languageserver-textdocument': [ '1.0.12' ],
62 silly audit   'vscode-uri': [ '3.0.8' ],
62 silly audit   'web-tree-sitter': [ '0.20.8' ],
62 silly audit   'vscode-languageserver-protocol': [ '3.17.3' ],
62 silly audit   'vscode-jsonrpc': [ '8.1.0' ],
62 silly audit   'vscode-languageserver-types': [ '3.17.3' ]
62 silly audit }
63 info run tree-sitter-twig@0.4.0 install node_modules/tree-sitter-twig node-gyp rebuild
64 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 305ms
65 silly audit report {}
66 info run tree-sitter-twig@0.4.0 install { code: 1, signal: null }
67 verbose stack Error: command failed
67 verbose stack     at promiseSpawn (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
67 verbose stack     at spawnWithShell (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
67 verbose stack     at promiseSpawn (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
67 verbose stack     at runScriptPkg (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
67 verbose stack     at runScript (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
67 verbose stack     at /home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
67 verbose stack     at run (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
67 verbose stack     at /home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
67 verbose stack     at new Promise (<anonymous>)
67 verbose stack     at callLimit (/home/vinicius/.nvm/versions/node/v22.11.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
68 verbose pkgid tree-sitter-twig@0.4.0
69 error code 1
70 error path /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig
71 error command failed
72 error command sh -c node-gyp rebuild
73 error gyp info it worked if it ends with ok
73 error gyp info using node-gyp@10.2.0
73 error gyp info using node@22.11.0 | linux | x64
73 error gyp info find Python using Python version 3.12.2 found at "/home/vinicius/Applications/anaconda3/bin/python3"
73 error gyp info spawn /home/vinicius/Applications/anaconda3/bin/python3
73 error gyp info spawn args [
73 error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/gyp/gyp_main.py',
73 error gyp info spawn args 'binding.gyp',
73 error gyp info spawn args '-f',
73 error gyp info spawn args 'make',
73 error gyp info spawn args '-I',
73 error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig/build/config.gypi',
73 error gyp info spawn args '-I',
73 error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/addon.gypi',
73 error gyp info spawn args '-I',
73 error gyp info spawn args '/home/vinicius/.cache/node-gyp/22.11.0/include/node/common.gypi',
73 error gyp info spawn args '-Dlibrary=shared_library',
73 error gyp info spawn args '-Dvisibility=default',
73 error gyp info spawn args '-Dnode_root_dir=/home/vinicius/.cache/node-gyp/22.11.0',
73 error gyp info spawn args '-Dnode_gyp_dir=/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp',
73 error gyp info spawn args '-Dnode_lib_file=/home/vinicius/.cache/node-gyp/22.11.0/<(target_arch)/node.lib',
73 error gyp info spawn args '-Dmodule_root_dir=/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig',
73 error gyp info spawn args '-Dnode_engine=v8',
73 error gyp info spawn args '--depth=.',
73 error gyp info spawn args '--no-parallel',
73 error gyp info spawn args '--generator-output',
73 error gyp info spawn args 'build',
73 error gyp info spawn args '-Goutput_dir=.'
73 error gyp info spawn args ]
73 error gyp: binding.gyp not found (cwd: /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig) while trying to load binding.gyp
73 error gyp ERR! configure error 
73 error gyp ERR! stack Error: `gyp` failed with exit code: 1
73 error gyp ERR! stack at ChildProcess.<anonymous> (/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/lib/configure.js:317:18)
73 error gyp ERR! stack at ChildProcess.emit (node:events:518:28)
73 error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
73 error gyp ERR! System Linux 6.8.0-49-generic
73 error gyp ERR! command "/home/vinicius/.nvm/versions/node/v22.11.0/bin/node" "/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/.bin/node-gyp" "rebuild"
73 error gyp ERR! cwd /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig
73 error gyp ERR! node -v v22.11.0
73 error gyp ERR! node-gyp -v v10.2.0
73 error gyp ERR! not ok
74 silly unfinished npm timer reify 1732711899546
75 silly unfinished npm timer reify:build 1732711914912
76 silly unfinished npm timer build 1732711914913
77 silly unfinished npm timer build:deps 1732711914913
78 silly unfinished npm timer build:run:install 1732711914915
79 silly unfinished npm timer build:run:install:node_modules/tree-sitter-twig 1732711914915
80 verbose cwd /home/vinicius/.local/share/zed/extensions/work/twig
81 verbose os Linux 6.8.0-49-generic
82 verbose node v22.11.0
83 verbose npm  v10.9.0
84 verbose exit 1
85 verbose code 1
86 error A complete log of this run can be found in: /home/vinicius/.local/share/zed/node/cache/_logs/2024-11-27T12_51_39_063Z-debug-0.log
```

</details>

It's been a few days and I haven't been able to resolve the conflict with this extension running on Ubuntu 24.04.1, does anyone have any idea how to resolve this issue?

**Comment by probably-neb** [comment]
Please open this as an issue on the Twig extension. Thanks!
